spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  cloud:
    vault:
      enabled: false
  vault:
    host: 127.0.0.1
    port: 8200
    scheme: http
    token: 

  servicenow:
    base-url: https://your-instance.service-now.com
    api-path: /api/now/table
    username: ${SERVICENOW_USERNAME:admin}
    password: ${SERVICENOW_PASSWORD:password}
    connection-timeout: 5000
    read-timeout: 10000
    
server:
  port: 8080

logging:
  level:
    com.example.certmgmt: DEBUG
